#!/bin/bash
# Example usage of new screenshot features for ContentBot

echo "================================================"
echo "ContentBot Screenshot Features - Example Usage"
echo "================================================"
echo ""

# Example 1: Basic Reddit video with screenshots (default)
echo "Example 1: Basic Reddit video with screenshots"
echo "-----------------------------------------------"
echo "Command: python create_video.py aita --reddit"
echo ""
echo "Features:"
echo "  - Captures Reddit post screenshot"
echo "  - Captures top 3 comment screenshots"
echo "  - Sequential display mode (default)"
echo "  - Fade-in, slide-up, and zoom-in animations"
echo ""
echo "================================================"
echo ""

# Example 2: Overlay display mode
echo "Example 2: Overlay display mode"
echo "--------------------------------"
echo "Command: python create_video.py aita --reddit --comment-display overlay"
echo ""
echo "Features:"
echo "  - All screenshots stacked vertically"
echo "  - Staggered fade-in animations"
echo "  - Shows post + comments simultaneously"
echo "  - Great for comparison videos"
echo ""
echo "================================================"
echo ""

# Example 3: Slide transitions
echo "Example 3: Slide transitions"
echo "----------------------------"
echo "Command: python create_video.py aita --reddit --comment-display slide"
echo ""
echo "Features:"
echo "  - Horizontal slide transitions"
echo "  - Smooth entrance from right"
echo "  - Dynamic, engaging transitions"
echo "  - Best for storytelling flow"
echo ""
echo "================================================"
echo ""

# Example 4: Screenshot positioning
echo "Example 4: Screenshot positioning"
echo "----------------------------------"
echo "Command: python create_video.py aita --reddit --screenshot-position top"
echo ""
echo "Features:"
echo "  - Screenshot positioned at top of video"
echo "  - Options: top, center, bottom"
echo "  - Useful for specific video layouts"
echo ""
echo "================================================"
echo ""

# Example 5: Combined options
echo "Example 5: Combined options"
echo "---------------------------"
echo "Command: python create_video.py relationship_drama --reddit --subreddit relationship_advice --screenshot-position center --comment-display sequential"
echo ""
echo "Features:"
echo "  - Custom subreddit selection"
echo "  - Center positioning"
echo "  - Sequential comment display"
echo "  - Fully customized workflow"
echo ""
echo "================================================"
echo ""

# Example 6: No screenshots (text subtitles)
echo "Example 6: Text subtitles instead of screenshots"
echo "------------------------------------------------"
echo "Command: python create_video.py aita --reddit --no-screenshots"
echo ""
echo "Features:"
echo "  - Falls back to text subtitles"
echo "  - Faster rendering"
echo "  - Good for testing or alternative style"
echo ""
echo "================================================"
echo ""

# Example 7: Multiple videos with different styles
echo "Example 7: Batch generation with different styles"
echo "--------------------------------------------------"
echo "# Sequential mode"
echo "python create_video.py aita --reddit --comment-display sequential"
echo ""
echo "# Overlay mode"
echo "python create_video.py aita --reddit --comment-display overlay"
echo ""
echo "# Slide mode"
echo "python create_video.py aita --reddit --comment-display slide"
echo ""
echo "Features:"
echo "  - Create multiple versions of same content"
echo "  - Test which style performs best"
echo "  - A/B testing for virality"
echo ""
echo "================================================"
echo ""

echo "✅ All examples ready to run!"
echo ""
echo "Pro Tips:"
echo "  1. Screenshots are cached - re-running is fast!"
echo "  2. Try different display modes to find your style"
echo "  3. Animations are automatic - no configuration needed"
echo "  4. Comments increase watch time and engagement"
echo "  5. Use --screenshot-position to match your branding"
echo ""
echo "================================================"
